### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by shadowzoom** [tugstugi/dl-colab-notebooks#14]
Hi guys! Can you please add into google colab image super resolution please? Like a gigapixel

**Comment by tugstugi** [comment]
like this? https://colab.research.google.com/github/idealo/image-super-resolution/blob/master/notebooks/ISR_Prediction_Tutorial.ipynb

**Comment by tugstugi** [comment]
see here: https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/ISR_Prediction_Tutorial.ipynb
