### ISSUE TITLE
Issues in Open_MMLab_Detection_Toolbox_Cascade_RCNN.ipynb

### ISSUE THREAD

**Issue by loveunk** [tugstugi/dl-colab-notebooks#15]
First, thanks for sharing.

I have encountered some issues to when running the notebook:
1. in latest mmdetection repo, no `compile.sh`, should change the script to:
`!cd mmdetection && python setup.py install`

2. imagecorruptions is not found, should install it first:
`!pip install imagecorruptions`

3. mmdetection's API has changed.
here's my modification: https://colab.research.google.com/drive/1l2_joRxe68DZBo6uDZ18gYuX6opseajI

**Comment by tugstugi** [comment]
thanks for reporting, I made small changes and copied your updated notebook into https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/Open_MMLab_Detection_Toolbox_Cascade_RCNN.ipynb
