### ISSUE TITLE
Add Mellotron?

### ISSUE THREAD

**Issue by scottbouma** [tugstugi/dl-colab-notebooks#17]
Wow this is a fantastic resource!  Thanks so much!  After running the Tacotron2/Waveglow one from Nvidia, I decided to try using it as a template to port this one to Colab as well:  https://github.com/NVIDIA/mellotron/blob/master/inference.ipynb

But of course I got bogged down quickly :)  Any chance you could port a version of the Mellotron jupyter notebook and add it to your list?  Thanks so much!

**Comment by tugstugi** [comment]
there is already a Mellotron notebook from someone else: https://colab.research.google.com/github/yhgon/mellotron/blob/master/inference_colab.ipynb

I put also the link in the README.md
