### ISSUE TITLE
Add Real-Time-Voice-Cloning?

### ISSUE THREAD

**Issue by htadashi** [tugstugi/dl-colab-notebooks#18]
Thanks for this fantastic resource. I think this collab on real time voice cloning could also be a nice addition to the list:
https://colab.research.google.com/drive/1ts-KRxOuuAHmb-AtjU1XTM_lIFOepAN2

**Comment by tugstugi** [comment]
tnx, I have updated the demo notebook little bit and uploaded it: https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/RealTimeVoiceCloning.ipynb

**Comment by 400lbhacker** [comment]
last step, error: "operands could not be broadcast together with shapes (2200,) (4000,) (2200,)" 
is this due to numpy version or python version(2/3) thanks

**Comment by tugstugi** [comment]
@400lbhacker fixed.

**Comment by aakashkumar6868** [comment]
Hey can u do it for adding paragraphs.

**Comment by 400lbhacker** [comment]
Hey tugstugi I just wanted to say thankyou for making this wonderful project, and for also resolving that issue. That is the fastest fix responce time ive ever had on github. keep up the wonderful project

**Comment by 400lbhacker** [comment]
I really want to talk to you im impressed with alot of your projects im new to github still learning how to use it, my email is here: josepherickson135@gmail.com my facebook is: https://www.facebook.com/profile.php?id=100015734717430

**Comment by himanshuragtah1** [comment]
> Hey can u do it for adding paragraphs.



> @400lbhacker fixed.
 
@tugstugi error: "operands could not be broadcast together with shapes (2200,) (4000,) (2200,)" occurring again. How can this be fixed?

**Comment by deanrussell** [comment]
Hi @tugstugi. On colab, I'm getting two errors in the final "Synthesize" step:

`FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-4-6e155181f8d0>](https://localhost:8080/#) in <module>()`

and

`FileNotFoundError: [Errno 2] No such file or directory: 'Real-Time-Voice-Cloning/saved_models/default/synthesizer.pt'`

Any thoughts on what I'm doing wrong?

**Comment by tugstugi** [comment]
@deanrussell Currently download from Google Drive doesn't work anymore, as long `gdown` doesn't fix it, we can't do anything, see: https://github.com/wkentaro/gdown/issues/162

**Comment by tugstugi** [comment]
@deanrussell you can try again, it is now hopefully fixed.

**Comment by deanrussell** [comment]
> @deanrussell you can try again, it is now hopefully fixed.

Thank you, @tugstugi! It works.

**Comment by Cybernite21** [comment]
Hi, this is a really great tool, but if I were to disconnect and reconnect, is there a way to reload the state the ai was in? So i do not have to re upload audio and retrain?

**Comment by KaliHUB10** [comment]
THANK YOU

**Comment by rwconsultancy** [comment]
I must be doing something wrong but I don't know what. Although my own recording is loud and clear, the generated voice is muffled and garbled - it rather sounds as if I'm talking gibberish with a sock in my mouth.

The installation moaned about needing a later version of numpy, so I gave it that, but that didn't change anything. I also had to change the line '%tensorflow_version 1.x' to '%tensorflow_version 2.x', otherwise it wouldn't install; I don't know if that has made a difference. There were no other errors.

Be gentle with me - I really have very little clue what I'm doing! I'm just looking for an easy way to clone my own voice. Thanks!

**Comment by KaliHUB10** [comment]
Thank YOU

12 Ağu 2022 Cum 14:51 tarihinde rwconsultancy ***@***.***>
şunu yazdı:

**Comment by souvikg544** [comment]
Will giving big audio files of maybe 5 hours help in getting a good output?

**Comment by lucidigital** [comment]
> tnx, I have updated the demo notebook little bit and uploaded it: https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/RealTimeVoiceCloning.ipynb

Google Colab said they don't support TensorFlow 1.x anymore, and require to update TensorFlow 2. Colab doc becomes useless :( Can you update it? Thanks

**Comment by jjpb44** [comment]
Must be upgraded to tensorflow 2 for compatibility with colab.

**Comment by AlbinoGeek** [comment]
For all the people mentioning tensorflow 2 support....

Just delete the line that mentions tensorflow 1.x -- it works.

@jujpenabe @lucidigital

**Comment by Abbienew** [comment]
My first attempt was successful, but the subsequent executions were unsuccessful and produced errors 
ModuleNotFoundError: No module named 'unidecode' ; NameError: name 'encoder' is not defined;" NameError: name 'encoder' is not defined " 

any solutions? tips?

**Comment by imvbhuvan** [comment]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-4-f993360f1d4d>](https://localhost:8080/#) in <cell line: 23>()
     28   #button = widgets.Button(description="Upload Voice File")
     29   #button.on_click(_upload_audio)
---> 30   _upload_audio("")

2 frames
[/content/Real-Time-Voice-Cloning/encoder/audio.py](https://localhost:8080/#) in preprocess_wav(fpath_or_wav, source_sr, normalize, trim_silence)
     40     # Resample the wav if needed
     41     if source_sr is not None and source_sr != sampling_rate:
---> 42         wav = librosa.resample(wav, source_sr, sampling_rate)
     43 
     44     # Apply the preprocessing: normalize volume and shorten long silences

TypeError: resample() takes 1 positional argument but 3 were given


 I am this error constantly any tips on how to resolve this @tugstugi

**Comment by roy-sub** [comment]
Hey [imvbhuvan](https://github.com/imvbhuvan) where you able to fix the  `TypeError: resample() takes 1 positional argument but 3 were given`.

If yes kindly provide the solution !
