### ISSUE TITLE
Issue with RealTimeVoiceCloning

### ISSUE THREAD

**Issue by anirudhcmohan** [tugstugi/dl-colab-notebooks#20]
I'm trying to run the colab notebook exactly as specified but keep running into this error after running the first command. I've tried uninstalling + reinstalling Tensorflow, but no luck!

Error:

ImportError                               Traceback (most recent call last)
<ipython-input-28-37953791cc59> in <module>()
     26 from dl_colab_notebooks.audio import record_audio, upload_audio
     27 
---> 28 from synthesizer.inference import Synthesizer
     29 from encoder import inference as encoder
     30 from vocoder import inference as vocoder

17 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/__init__.py in <module>()
     31 from tensorflow.python.keras.saving.save import load_model
     32 from tensorflow.python.keras.saving.save import save_model
---> 33 from tensorflow.python.keras.saving.saved_model import export_saved_model
     34 from tensorflow.python.keras.saving.saved_model import load_from_saved_model
     35 from tensorflow.python.keras.saving.saving_utils import trace_model_call

ImportError: cannot import name 'export_saved_model'

**Comment by anirudhcmohan** [comment]
I got it to work, never mind!

Ran the following:

%tensorflow_version 1.x
import tensorflow

**Comment by tugstugi** [comment]
fixed in the notebook now: https://github.com/tugstugi/dl-colab-notebooks/commit/67caaeb668aa6b596b4ad3df2acf15228b5ba0be
