### ISSUE TITLE
Error on LipGAN notebook 

### ISSUE THREAD

**Issue by htadashi** [tugstugi/dl-colab-notebooks#22]
Running the 5th line from [LipGAN notebook](https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/LipGAN.ipynb) returns the following error:

```
#@title  
!rm -rf *.avi  
!cd {project_name} && python batch_inference.py --checkpoint_path logs/lipgan_residual_mel.h5 --face ../{image_name} --fps 30 --audio ../{audio_name} --results_dir ..
```

> 2020-04-24 14:55:27.562365: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
> Traceback (most recent call last):
>   File "batch_inference.py", line 3, in <module>
>     import scipy, cv2, os, sys, argparse, audio
>   File "/content/LipGAN/audio.py", line 7, in <module>
>     from audio_hparams import hparams as hp
>   File "/content/LipGAN/audio_hparams.py", line 1, in <module>
>     from tensorflow.contrib.training import HParams
> ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by tugstugi** [comment]
should be fixed now by https://github.com/tugstugi/dl-colab-notebooks/commit/fa68f8bbb2d90d577645d4c7742915e1bc4a4ec2

The problem was that Colab uses now per default Tensorflow2.

**Comment by htadashi** [comment]
@tugstugi  Thanks! I always wanted to run this code on Colab :)
