### ISSUE TITLE
Slow Mo colab not working

### ISSUE THREAD

**Issue by scienceapps** [tugstugi/dl-colab-notebooks#24]
Hello, 

The slow motion colab doesn't work. I get MKV error conversion. Can you help me ?

https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/SuperSloMo.ipynb

Best regards

**Comment by tugstugi** [comment]
fixed by https://github.com/tugstugi/dl-colab-notebooks/commit/85ab593dc9c85fbba9aa699a3565d26ac2ead97e
