### ISSUE TITLE
OpenPose giving errors. 

### ISSUE THREAD

**Issue by murugeshmanthiramoorthi** [tugstugi/dl-colab-notebooks#25]
The installation is completed. But When I try to execute the model on the youtube videos, it shows "NO such file or directory found"

**Comment by tugstugi** [comment]
the server which hosts the OpenPose pretrained models is down. See this ticket: https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1576

**Comment by murugeshmanthiramoorthi** [comment]
Thank you so much. Now it is normal.
