### ISSUE TITLE
CenterNet Objects as Points DCNv2 compilation error 

### ISSUE THREAD

**Issue by xun468** [tugstugi/dl-colab-notebooks#26]
Hey! I'm trying to check out the CenterNet notebook but I am getting a compilation error when I run the first code block. Is this something on my end? The runtime has a GPU and I've confirmed that cuda is installed and !nvcc --version returns 

`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
`

The error is extremely long and seems to be mostly depreciation errors, but here is the tail end. 

> `/content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:398:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’
>    AT_DISPATCH_FLOATING_TYPES(out_grad.type(), "dcn_v2_psroi_pooling_cpu_backward", [&] {
>    ^~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
>                  from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
>                  from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
>                  from /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:15:
> /usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:341:7: note: declared here
>    T * data() const {
>        ^~~~
> In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:9:0,
>                  from /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:15:
> /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:412:48: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
>          trans_grad.contiguous().data<scalar_t>(),
>                                                 ^
> /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Dispatch.h:12:12: note: in definition of macro ‘AT_PRIVATE_CASE_TYPE’
>      return __VA_ARGS__();                          \
>             ^~~~~~~~~~~
> /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:398:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’
>    AT_DISPATCH_FLOATING_TYPES(out_grad.type(), "dcn_v2_psroi_pooling_cpu_backward", [&] {
>    ^~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
>                  from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
>                  from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
>                  from /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:15:
> /usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:341:7: note: declared here
>    T * data() const {
>        ^~~~
> In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:9:0,
>                  from /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:15:
> /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:413:43: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
>          input.contiguous().data<scalar_t>(),
>                                            ^
> /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Dispatch.h:12:12: note: in definition of macro ‘AT_PRIVATE_CASE_TYPE’
>      return __VA_ARGS__();                          \
>             ^~~~~~~~~~~
> /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:398:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’
>    AT_DISPATCH_FLOATING_TYPES(out_grad.type(), "dcn_v2_psroi_pooling_cpu_backward", [&] {
>    ^~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
>                  from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
>                  from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
>                  from /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:15:
> /usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:341:7: note: declared here
>    T * data() const {
>        ^~~~
> In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:9:0,
>                  from /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:15:
> /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:414:42: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
>          bbox.contiguous().data<scalar_t>(),
>                                           ^
> /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Dispatch.h:12:12: note: in definition of macro ‘AT_PRIVATE_CASE_TYPE’
>      return __VA_ARGS__();                          \
>             ^~~~~~~~~~~
> /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:398:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’
>    AT_DISPATCH_FLOATING_TYPES(out_grad.type(), "dcn_v2_psroi_pooling_cpu_backward", [&] {
>    ^~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
>                  from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
>                  from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
>                  from /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:15:
> /usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:341:7: note: declared here
>    T * data() const {
>        ^~~~
> In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:9:0,
>                  from /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:15:
> /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:415:43: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
>          trans.contiguous().data<scalar_t>(),
>                                            ^
> /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Dispatch.h:12:12: note: in definition of macro ‘AT_PRIVATE_CASE_TYPE’
>      return __VA_ARGS__();                          \
>             ^~~~~~~~~~~
> /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:398:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’
>    AT_DISPATCH_FLOATING_TYPES(out_grad.type(), "dcn_v2_psroi_pooling_cpu_backward", [&] {
>    ^~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
>                  from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
>                  from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
>                  from /content/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.cpp:15:
> /usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:341:7: note: declared here
>    T * data() const {
>        ^~~~
> /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/content/CenterNet/src/lib/models/networks/DCNv2/src -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c /content/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_im2col_cuda.cu -o build/temp.linux-x86_64-3.6/content/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_im2col_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_60,code=sm_60 -std=c++14
> /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/content/CenterNet/src/lib/models/networks/DCNv2/src -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c /content/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu -o build/temp.linux-x86_64-3.6/content/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_60,code=sm_60 -std=c++14
> /content/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu(107): error: identifier "THCState_getCurrentStream" is undefined
> 
> /content/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu(279): error: identifier "THCState_getCurrentStream" is undefined
> 
> 2 errors detected in the compilation of "/tmp/tmpxft_000000e6_00000000-6_dcn_v2_cuda.cpp1.ii".
> error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
>   Building wheel for progress (setup.py) ... done`

**Comment by tugstugi** [comment]
fixed by https://github.com/tugstugi/dl-colab-notebooks/commit/5ab96adb5651de1e6679a2ce7b84f2675adebeb7
