### ISSUE TITLE
AlphaPose v0.3.0 - No module named 'detector'

### ISSUE THREAD

**Issue by Ritchizh** [tugstugi/dl-colab-notebooks#27]
Hi! When running the notebook 'AlphaPhose v0.3.0' as it is, at performing detection on the cut 'video.avi', the line:

`!cd {project_name} && python3 scripts/demo_inference.py --sp --video ../video.avi --outdir ../ --save_video --checkpoint ../{pretrained_model_path} --cfg ../{pretrained_model_config_path}`

I get the error:

```
File "scripts/demo_inference.py", line 12, in <module>
    from detector.apis import get_detector
ModuleNotFoundError: No module named 'detector'
```
So, it tries to run 'demo_inference.py', but can't do the imports.
Could you please clarify what could be the reason for this error? Should I add some paths to the working directory?
(* the other notebook 'AlphaPose.ipynb' runs fine)

**Comment by tugstugi** [comment]
Colab uses now PyTorch 1.5 which makes trouble for AlphaPose. I have  downgraded the PyTorch version. Should be fixed now by https://github.com/tugstugi/dl-colab-notebooks/commit/c2278f33a3127fd098bd89cb65a19cd1e614b7f8

**Comment by adel6666** [comment]
I have the same error while executing the code locally on my machine, is there another solution for me please?
