### ISSUE TITLE
RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by Ericksgeo** [tugstugi/dl-colab-notebooks#29]
Hello, I am using the Semantic segmentation trained on ADE20K using CSAILVision/semantic-segmentation-pytorch. After some tests, I am having this RuntimeError: CUDA out of memory. I was reading about the bach size but I am not sure how your implementation deals with it, and how to change the code to accept a larger image. I am running the code in Colab. 

Thanks for your help.

**Comment by tugstugi** [comment]
It is inferencing so batch size is 1. It sounds like you are using a too big image. Try to resize your image into smaller resolution and try again.
