### ISSUE TITLE
Add image-gpt

### ISSUE THREAD

**Issue by Kreijstal** [tugstugi/dl-colab-notebooks#31]
https://github.com/openai/image-gpt/issues/2

Image gpt adds autocompletition for images
![image](https://user-images.githubusercontent.com/2415206/85001327-cbee1080-b153-11ea-87f3-3bba43ffaad3.png)
https://openai.com/blog/image-gpt/
now that'd be cool

**Comment by JonathanFly** [comment]
https://gist.github.com/JonathanFly/eb61f0d31680e1b890f3a53fbaf31384

**Comment by tugstugi** [comment]
I have added https://colab.research.google.com/github/apeguero1/image-gpt/blob/master/Image_GPT_Sample_with_Conditioning.ipynb which seems to be a modified version of the JonathanFly's notebook.
