### ISSUE TITLE
import cv2 error in DENSEPOSE colab notebook

### ISSUE THREAD

**Issue by smithee771** [tugstugi/dl-colab-notebooks#33]
Hi tugstugi,
I'm trying to run "DensePose.ipynb". When I run the step "Detect poses on a test image" I get this error:
"must import cv2 before caffe2 due to bug in cv2."

Any clue on how to fix this?
Many thanks for your notebooks!

**Comment by tugstugi** [comment]
should be fixed now by https://github.com/tugstugi/dl-colab-notebooks/commit/6e6fc01919a844255d663fc82fbc3279d2d77e0b
