### ISSUE TITLE
Openpose 3D?

### ISSUE THREAD

**Issue by emilyjiayaoli** [tugstugi/dl-colab-notebooks#35]
Is it possible to add the code for 3d pose estimation for openpose? Thanks!

**Comment by tugstugi** [comment]
You need synchronized videos from multiple cameras for the 3D pose estimation? So not possible with youtube videos.

**Comment by emilyjiayaoli** [comment]
I believe that OpenPose is also able to convert the 2D keypoints to 3D key points. For example, here is one of the outputs I got from the google collab file, there are spots on the bottom for 3D estimation outputs: 

{"version":1.3,"people":[{"person_id":[-1],"pose_keypoints_2d":[227.422,57.1933,0.807357,223.511,94.3978,0.836523,199.092,96.3215,0.78966,183.361,121.801,0.765163,221.543,123.734,0.409549,247.021,92.4693,0.772991,277.3,118.86,0.825382,238.157,121.775,0.597572,223.546,166.785,0.40645,206.9,165.793,0.385908,167.732,200.047,0.306381,217.641,221.564,0.220226,240.152,167.76,0.36812,226.453,234.278,0.324446,221.521,295.894,0.258676,220.59,51.3234,0.880818,231.294,50.3888,0.933751,207.915,57.1995,0.841758,236.202,52.3695,0.181712,0,0,0,0,0,0,216.672,301.758,0.208005,0,0,0,0,0,0,218.622,219.598,0.104589],"face_keypoints_2d":[],"hand_left_keypoints_2d":[],"hand_right_keypoints_2d":[],"pose_keypoints_3d":[],"face_keypoints_3d":[],"hand_left_keypoints_3d":[],"hand_right_keypoints_3d":[]}]}

Thank you so much!
