### ISSUE TITLE
Versions of Tensorflow for Flowtron+Waveglow

### ISSUE THREAD

**Issue by ghost** [tugstugi/dl-colab-notebooks#38]
Hi, I wanted to understand why tensorflow 1.x was loaded instead of the current version.  In Nvidia's requirements they list tensorboardx . 
I'm new to these things and so want to understand what's really going on here.  Thank you!

**Comment by tugstugi** [comment]
I think Tacotron was using `tf.contrib.training.HParams` which was only available in the Tensorflow1.

**Comment by ishandutta2007** [comment]
@tugstugi Please update the imports . 
I think they have remove tensorflow1 from pypi.
Almost all the TTS that I tried are failing for all the codelabs.

**Comment by tugstugi** [comment]
@ishandutta2007 which notebooks fail?

**Comment by okyanusoz** [comment]
RealTimeVoiceCloning seems to fail because of TF1.

**Comment by ishandutta2007** [comment]
> notebooks

I already mentioned "all"
