### ISSUE TITLE
3 Errors in Cell 1

### ISSUE THREAD

**Issue by Hazyyyyy** [tugstugi/dl-colab-notebooks#41]
ERROR: tensorflow 1.15.2 has requirement gast==0.2.2, but you'll have gast 0.3.3 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.

**Comment by tugstugi** [comment]
Which notebook?

**Comment by tugstugi** [comment]
Those are warnings. The code should still work.
