### ISSUE TITLE
EAST notebook

### ISSUE THREAD

**Issue by shersoni610** [tugstugi/dl-colab-notebooks#43]
Hi,

The following error message pops-up while running the EAST detector notebook.

021-04-10 04:06:17.612089: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
make: Entering directory '/content/EAST/lanms'
g++ -o adaptor.so -I include  -std=c++11 -O3 -I/usr/include/python3.6m -I/usr/include/python3.6m  -Wno-unused-result -Wsign-compare -g -fdebug-prefix-map=/build/python3.6-1chSKv/python3.6-3.6.9=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -L/usr/lib -lpython3.6m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions adaptor.cpp include/clipper/clipper.cpp --shared -fPIC
In file included from include/pybind11/pytypes.h:12:0,
                 from include/pybind11/cast.h:13,
                 from include/pybind11/attr.h:13,
                 from include/pybind11/pybind11.h:43,
                 from adaptor.cpp:1:
adaptor.cpp: In function ‘PyObject* PyInit_adaptor()’:
include/pybind11/common.h:232:34: warning: ‘PyObject* pybind11_init()’ is deprecated: PYBIND11_PLUGIN is deprecated, use PYBIND11_MODULE [-Wdeprecated-declarations]
             return pybind11_init();                                            \
                                  ^
adaptor.cpp:53:1: note: in expansion of macro ‘PYBIND11_PLUGIN’
 PYBIND11_PLUGIN(adaptor) {
 ^~~~~~~~~~~~~~~
include/pybind11/common.h:217:22: note: declared here
     static PyObject *pybind11_init();                                          \
                      ^
adaptor.cpp:53:1: note: in expansion of macro ‘PYBIND11_PLUGIN’
 PYBIND11_PLUGIN(adaptor) {
 ^~~~~~~~~~~~~~~
include/clipper/clipper.cpp: In member function ‘void ClipperLib::Clipper::FixupFirstLefts3(ClipperLib::OutRec*, ClipperLib::OutRec*)’:
include/clipper/clipper.cpp:3665:13: warning: unused variable ‘firstLeft’ [-Wunused-variable]
     OutRec* firstLeft = ParseFirstLeft(outRec->FirstLeft);
             ^~~~~~~~~
make: Leaving directory '/content/EAST/lanms'
Traceback (most recent call last):
  File "eval.py", line 11, in <module>
    tf.app.flags.DEFINE_string('test_data_path', '/tmp/ch4_test_images/images/', '')
AttributeError: module 'tensorflow' has no attribute 'app'
Now, visualize the result:

[5]
plt.figure(figsize=(20, 26))
plt.imshow(matplotlib.image.imread(image_file_name))

**Comment by tugstugi** [comment]
It was a TF 1 and Python3.7 problem, I have fixed with https://github.com/tugstugi/dl-colab-notebooks/commit/7573686bbdefd3784dacbe4dee1495ac24eb444e
