### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by santhosh10972** [tugstugi/dl-colab-notebooks#48]
These errors are occurring when I run Setup CorentinJ/Real-Time-Voice-Cloning
ERROR: tensorflow 1.15.2 has requirement gast==0.2.2, but you'll have gast 0.4.0 which is incompatible.
ERROR: lucid 0.3.10 has requirement numpy<=1.19, but you'll have numpy 1.19.4 which is incompatible.
ERROR: kapre 0.3.5 has requirement tensorflow>=2.0.0, but you'll have tensorflow 1.15.2 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.

**Comment by tugstugi** [comment]
It is only a warning, the code should still work.
