### ISSUE TITLE
CenterNet (Objects as Points) demo

### ISSUE THREAD

**Issue by melaniihariono** [tugstugi/dl-colab-notebooks#50]
Hello.
Iam trying to run the centernet demo. When I change the model to Centernet hourglass, then I found this. Can anyone tell me what is this?
Thanks!

**Comment by tugstugi** [comment]
* dowload first the correct weight:
```
model_name = 'ctdet_coco_hg.pth'
if not exists(model_name):
  !pip install -q gdown
  !gdown 'https://drive.google.com/uc?id=1cNyDmyorOduMRsgXoUnuyUiF6tZNFxaG'
```
* change the model architecture to hourglass:
```
opt.load_model = model_name
opt.arch = 'hourglass'
```

It should work now as intended.
