### ISSUE TITLE
Real-Time Voice Cloning dependencies issue?

### ISSUE THREAD

**Issue by RobertoPuglieseFusco** [tugstugi/dl-colab-notebooks#52]
Hello and thanks for your extensive repo of examples!

I was trying the real-time voice cloning and bounced into this error:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 1.15.2 requires gast==0.2.2, but you have gast 0.4.0 which is incompatible.
lucid 0.3.10 requires numpy<=1.19, but you have numpy 1.20.3 which is incompatible.
yellowbrick 1.3.post1 requires numpy<1.20,>=1.16.0, but you have numpy 1.20.3 which is incompatible.
kapre 0.3.6 requires tensorflow>=2.0.0, but you have tensorflow 1.15.2 which is incompatible.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.

Unfortunately I don't know enough of library versioning to fix it myself if you could give me some guidelines...

Thank you!

Roberto

**Comment by tugstugi** [comment]
@RobertoPuglieseFusco this errors shouldn't affect the voice cloning. I have fixed the Google Drive issue, the demo should work now.

**Comment by RobertoPuglieseFusco** [comment]
Thank you very much for your answer!
I will try again to go through the colab.

Thanks again
